name: Docker Build and Scan

on:
  push: null
    # branches:
    #   - main
  pull_request: null

permissions: {}

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          fetch-depth: 0
          context: .
          load: true
          tags: my-app:latest

      - name: Save Docker image as tar
        run: docker save -o my-app.tar my-app:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-app.tar

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i my-app.tar

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: my-app:latest
          severity_threshold: HIGH
