---
name: Docker Build

on:
  push:
    null
    # branches:
    #   - main
  pull_request: null

permissions: {}

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          fetch-depth: 0
          context: .
          push: true
          tags: user/app:latest

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: user/app:latest
          severity_threshold: HIGH
